#+TITLE: Readme

This is a small library that can be used
to remove the unused macros from the sombrero codebase
- that is,
from the ~suN.h~-like and ~suN_repr_func.h~-like
files.
New versions of those files are produced
that can replace the ones in the original directory.
Just run

#+BEGIN_SRC bash
$ python ./main.py <rootdir> <tmpdir>
#+END_SRC

Where ~<rootdir>~ is the directory
that contains sombrero
and the files that need to be cleaned,
and ~<tmpdir>~ is a directory that
will be used to store the results
and temporary files.

This command will create 4 directories.
As far as sombrero packaging is concerned,
we only need the files in the
~*_by_grouprep~ directories.

The files in that directory
can be moved back
to the ~Include~ directory
in the Sombrero repository.

A ~replace_macros.sh~ script is provided
that does all of this.
#+BEGIN_SRC bash
$ ./replace_macros.sh <rootdir>
#+END_SRC
In this case,
the temporary directory
that will be passed to ~main.py~
will be the directory
where the ~replace_macros.sh~ is located.

In this case,
a backup
of the old version
of the files containing macros
will be placed where the script is located. 

* Details

The set of the 4 directories
produced running ~main.py~ 
is the cartesian product of two choices:
- macros for the fundamental vs macros for the representation
  (e.g., ~suN.h~ vs ~suN_repr_func.h~)
- files containing macros grouped ~by_name~ or grouped by version
  (group and representation, ~by_grouprep~)

In addition to the 4 directories,
a list of macros in use
(matching the list of files
contained in the ~macros~ directory)
will be written in the ~used_macros.txt~ file
and in the ~used_macros_repr_func.txt~ file.
